/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummary } from '../models/user-summary';
export interface AuthUserResponse {
  accessToken?: string;
  expiresIn?: number;
  issuedAt?: number;
  tokenType?: string;
  user?: UserSummary;
}
