/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  content?: string;
  createdAt?: string;
  id?: string;
  media?: Array<string>;
  senderId?: string;
  seenBy?: string[];
  type?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO';
}
