/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserRequest {
  email: string;
  firstName: string;
  lastName: string;
  password?: string;
  phoneNumber?: string;
}
